### ISSUE TITLE
Not more bootstrap.php.cache in symfony 4

### ISSUE THREAD

**Issue by pedroresende** [piotrpolak/codeigniter-symfony2-bridge#1]
Apparently Symfony 4 doesn't have `bootstrap.php.cache`. Is it possible to remove this dependency ?

**Comment by piotrpolak** [comment]
Could you please create a PR for that?

**Comment by pedroresende** [comment]
@piotrpolak Sorry, I'll close the issue. Since it's invalid, or should I say border line. It will only affect who "migrated" from Symfony 2 to 3 and then to 4 and kept the old folder structure.
